
EXO_DB_HOST="localhost:3306"
EXO_DB_USER="dbuser"
EXO_DB_PASSWORD="dbpass"

export EXO_DB_HOST EXO_DB_USER EXO_DB_PASSWORD

TENANT_MASTERHOST="cloud-workspaces"
CLOUD_AGENT_USERNAME="cloudadmin"
CLOUD_AGENT_PASSWORD="cloudadmin"

export TENANT_MASTERHOST CLOUD_AGENT_USERNAME CLOUD_AGENT_PASSWORD

CLOUD_MAIL_HOST="smtp.gmail.com"
CLOUD_MAIL_PORT="465"
CLOUD_MAIL_SSL="true"
CLOUD_MAIL_USER="exo.plf.cloud.test1@gmail.com"
CLOUD_MAIL_PASSWORD="exo.plf.cloud.test112321"
CLOUD_MAIL_SMTP_AUTH="true"
CLOUD_ADMIN_EMAIL="exo.plf.cloud.test1@gmail.com"
CLOUD_LOGGER_EMAIL="exo.plf.cloud.test1@gmail.com"
CLOUD_SUPPORT_EMAIL="exo.plf.cloud.test1@gmail.com"
CLOUD_SUPPORT_SENDER="exo.plf.cloud.test1@gmail.com"
CLOUD_SALES_EMAIL="exo.plf.cloud.test1@gmail.com"

export CLOUD_MAIL_HOST CLOUD_MAIL_PORT CLOUD_MAIL_SSL CLOUD_MAIL_USER CLOUD_MAIL_PASSWORD CLOUD_MAIL_SMTP_AUTH CLOUD_ADMIN_EMAIL CLOUD_LOGGER_EMAIL CLOUD_SUPPORT_EMAIL CLOUD_SUPPORT_SENDER CLOUD_SALES_EMAIL

APPLICATION_DEFAULT_TYPE="local-cloud-agent"
CLOUD_SERVICE_TYPE="com.exoplatform.platform.cloud.admin.connector.LocalhostCloudServerClient"
CLOUD_CLIENT_NAME="localhost"
CLOUD_AWS_VERSION="2011-05-15"
CLOUD_AWS_IDENTITY=
CLOUD_AWS_CREDENTIALS=

export CLOUD_APPLICATION_DEFAULT_TYPE CLOUD_SERVICE_TYPE CLOUD_CLIENT_NAME CLOUD_AWS_VERSION CLOUD_AWS_IDENTITY CLOUD_AWS_CREDENTIALS

AS_INSTANCE_TYPE="m1.large"
AS_IMAGE_ID=
AS_AVAILABILITY_ZONE=
AS_SECURITY_GROUP_NAME=
AS_KEY_NAME=

export AS_INSTANCE_TYPE AS_IMAGE_ID AS_AVAILABILITY_ZONE AS_SECURITY_GROUP_NAME AS_KEY_NAME
